[profile.default]
gas_reports = ["MolekMarket"]
libs = ["lib"]
out = "out"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
]
solc_version = "0.8.20"
src = "src"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
